baseURL = "https://notmet.net/"
languageCode = "en-us"
title = "notmet.net"
theme = "ticky_tacky_dark"
googleAnalytics = "UA-42117518-1"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    favicon = "favicon.ico"
    description = "The homepage for kc0bfv@notmet.net and his wacky projects."
    images = [
        "/img/header01.jpg",
        "/img/header02.jpg",
        "/img/header03.jpg",
        "/img/header04.jpg",
        "/img/header05.jpg",
        "/img/header06.jpg",
        "/img/header07.jpg",
        "/img/header08.jpg",
        ]
    headername = "notmetdotnet"
    #msvalidate = ""
    #googlesiteverification = ""

[Author]
    name = "Karl Sickendick"
    email = "kc0bfv@notmet.net"
    [Author.Social]
        twitter = "kc0bfv"
        facebook = "karl.sickendick"
