baseURL = "http://notmet.net/"
languageCode = "en-us"
title = "notmet.net"
theme = "ticky_tacky_dark"
googleAnalytics = "UA-42117518-1"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
    favicon = "favicon.ico"
    webmasterEmail = "kc0bfv@notmet.net"
    headerimages = ["/img/header01.jpg", "/img/header02.jpg", "/img/header03.jpg", "/img/header04.jpg"]
    #msvalidate = ""
    #googlesiteverification = ""
